function centroid = computeCentroid(profile)
area = 0.5*sum(profile.panels.centre.X(1:end-1).*profile.panels.centre.Y(2:end)...
              -profile.panels.centre.X(2:end).*profile.panels.centre.Y(1:end-1));
centroid.x = (1/(6*area))*sum((profile.panels.centre.X(1:end-1)+profile.panels.centre.X(2:end))...
                            .*(profile.panels.centre.X(1:end-1).*profile.panels.centre.Y(2:end)...
                              -profile.panels.centre.X(2:end).*profile.panels.centre.Y(1:end-1)));
centroid.y = (1/(6*area))*sum((profile.panels.centre.Y(1:end-1)+profile.panels.centre.Y(2:end))...
                            .*(profile.panels.centre.X(1:end-1).*profile.panels.centre.Y(2:end)...
                              -profile.panels.centre.X(2:end).*profile.panels.centre.Y(1:end-1)));

end